version: "3"

services:
  app:
    container_name: hot-reload-express-ts
    restart: always
    build:
      context: .
      dockerfile: Dockerfile.dev
      args:
        - PORT=${PORT}
    volumes:
      - ./:/app
      - ignore:/app/node_nodules/
    expose:
      - 3000
    ports:
      - 3000:${PORT}
    env_file:
      - .env
volumes:
  ignore: